name = "cf-spotify"
main = "./.output/server/index.mjs"
compatibility_date = "2022-12-04"
env = { }

rules = [
  { type = "ESModule", globs = ["**/*.js", "**/*.mjs"]},
]

[site]
bucket = ".output/public"

[triggers]
crons = [ ]

# [secrets]
# NITRO_CLIENT_ID
# NITRO_CLIENT_SECRET
